//! TB-G G1.2-4 (Option B+ orchestration ruling 2026-05-11; binding directive
//! `handover/directives/2026-05-11_TB_G_G1_2_OPTION_B_PLUS_RULING.md` §3.3):
//! `BatchContinuationManifest` — the architect-mandated fact-identity for
//! a multi-task batch. Without this manifest, "same batch" has no
//! canonical reconstruction; the dashboard would merely stitch
//! independent runs together.
//!
//! Architect §3.3 verbatim:
//!
//! > 新增 BatchContinuationManifest. 这个 manifest 进入 CAS, 并由最后
//! > 的 TerminalSummaryTx 或 BatchSummaryTx 引用. 否则 dashboard 仍然
//! > 只是把多个 runs 拼起来，不是真实 batch.
//!
//! Schema is stable across G1.2..G7 atoms (`schema_version =
//! "g1_2_v1"`). The G1.2-3 orchestrator writes the manifest to disk
//! as it runs; G1.2-4 promotes the in-memory shape to a strongly-typed
//! struct that can also land as a Generic CAS object (so future
//! `TerminalSummaryTx.batch_continuation_manifest_cid` can anchor it).
//!
//! Four gates SG-G1.2-4.1..G1.2-4.4:
//!  1. manifest_records_all_tasks_in_order
//!  2. manifest_head_chain_is_continuous
//!  3. manifest_rejects_continuity_gap
//!  4. manifest_replay_matches_real_chain_head_walk
//!
//! FC-trace: FC2-Boot (cross-task chain-continuity proof) + FC3-Markov
//! (CAS-anchored derived view — manifest is materialised from the
//! chain, not a parallel ledger).

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::bottom_white::cas::schema::{Cid, ObjectType};
use crate::bottom_white::cas::store::{CasError, CasStore};
use crate::bottom_white::ledger::transition_ledger::{Git2LedgerWriter, LedgerWriter};

/// TRACE_MATRIX § 3 orphan (TB-G G1.2-4 2026-05-11; Option B+ §3.3):
/// canonical multi-task batch manifest. `tasks` carries one
/// `TaskContinuationEntry` per executed task in commit order.
/// Constitutional Justification:
/// `handover/directives/2026-05-11_TB_G_G1_2_OPTION_B_PLUS_RULING.md` §3.3.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BatchContinuationManifest {
    /// Stable schema version. G1.2 ships v1; later atoms (G3.4
    /// PnL anchor / G4.2 model-manifest-cid wiring) bump this to v2.
    pub schema_version: String,
    /// Batch identity (sha256 hex or human slug).
    pub batch_id: String,
    /// Filesystem path to the shared runtime_repo. Carried for
    /// human/auditor reference; the chain itself is the
    /// canonical proof.
    pub runtime_repo: String,
    /// Filesystem path to the shared CAS root. Same disclaimer.
    pub cas_root: String,
    /// Model identifier the batch ran under (e.g. "deepseek-chat").
    /// G4.2 will replace this scalar with a model-manifest CID.
    pub model: String,
    /// Agent count for the batch. Stable across tasks (Option B+ §1
    /// "no memory-only cross-task state" — same agent registry
    /// across the whole batch).
    pub n_agents: usize,
    /// Head OID hex BEFORE task_0 (empty string = fresh genesis).
    /// G1.2-4 records this so replay can verify the first task
    /// started from the architect-named "exactly one genesis"
    /// state.
    pub initial_head_t_hex: String,
    /// Optional CID of the agent-pubkeys manifest used by the batch.
    /// Populated when the orchestrator hashes
    /// `<runtime_repo>/agent_pubkeys.json` and writes it to CAS;
    /// `None` permitted for in-process tests.
    pub agent_registry_cid_hex: Option<String>,
    /// Optional CID of the pinned-pubkeys manifest. Same
    /// nullability semantics as `agent_registry_cid_hex`.
    pub system_pubkeys_cid_hex: Option<String>,
    /// Optional CID of a G4.2 model-assignment manifest. `None`
    /// until G4.2 lands.
    pub model_manifest_cid_hex: Option<String>,
    /// Optional CID of a REAL-5 role-assignment manifest. This preserves
    /// replayable role identity for continuation/resume batches without
    /// placing role state in EconomicState.
    #[serde(default)]
    pub role_assignment_manifest_cid_hex: Option<String>,
    /// Per-task entries in commit order.
    pub tasks: Vec<TaskContinuationEntry>,
    /// `None` on clean batch close; populated with the architect
    /// §3.5 halt-and-record reason on subprocess crash.
    pub terminated_reason: Option<String>,
}

/// TRACE_MATRIX § 3 orphan (TB-G G1.2-4 2026-05-11; Option B+ §3.3):
/// one task's continuation row. Stable shape — G1.2-3 orchestrator
/// already writes this layout under
/// `<out_dir>/BatchContinuationManifest.json`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TaskContinuationEntry {
    pub task_index: u64,
    pub problem_id: String,
    pub start_head_t_hex: String,
    pub end_head_t_hex: String,
    pub start_chain_length: u64,
    pub end_chain_length: u64,
    /// sha256 hex of the subprocess command line + canonical env
    /// subset. Empty when the entry was generated by an
    /// in-process test (no subprocess fired).
    pub subprocess_command_sha256: String,
    /// CID of a per-task `RunSummary` CAS object when written.
    /// G1.2-4 leaves this `None`; G3.4 wires it.
    pub run_summary_cid_hex: Option<String>,
    /// `tx_id` of the terminal-state transaction emitted for this
    /// task (e.g. `TerminalSummaryTx`). `None` when the subprocess
    /// crashed before emission.
    pub terminal_tx_id: Option<String>,
    pub exit_code: i32,
    pub started_at_unix_s: i64,
    pub finished_at_unix_s: i64,
}

/// TRACE_MATRIX § 3 orphan (TB-G G1.2-4 2026-05-11; Option B+ §3.3):
/// chain-continuity verifier. Returns Ok iff:
/// 1. `tasks[0].start_head_t_hex == initial_head_t_hex` (the batch
///    actually started from the recorded genesis)
/// 2. `tasks[k+1].start_head_t_hex == tasks[k].end_head_t_hex`
///    for every consecutive pair.
pub fn replay_continuity(manifest: &BatchContinuationManifest) -> Result<(), ContinuityFailure> {
    if let Some(first) = manifest.tasks.first() {
        if first.start_head_t_hex != manifest.initial_head_t_hex {
            return Err(ContinuityFailure::FirstTaskDoesNotMatchInitial {
                initial_head_t_hex: manifest.initial_head_t_hex.clone(),
                first_task_start: first.start_head_t_hex.clone(),
            });
        }
    }
    for (i, pair) in manifest.tasks.windows(2).enumerate() {
        if pair[1].start_head_t_hex != pair[0].end_head_t_hex {
            return Err(ContinuityFailure::Gap {
                at_pair_index: i,
                task_k_index: pair[0].task_index,
                task_k_end: pair[0].end_head_t_hex.clone(),
                task_k_plus_1_index: pair[1].task_index,
                task_k_plus_1_start: pair[1].start_head_t_hex.clone(),
            });
        }
    }
    Ok(())
}

/// TRACE_MATRIX § 3 orphan (TB-G G1.2-4 2026-05-11; Option B+ §3.3):
/// continuity-failure carrier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ContinuityFailure {
    FirstTaskDoesNotMatchInitial {
        initial_head_t_hex: String,
        first_task_start: String,
    },
    Gap {
        at_pair_index: usize,
        task_k_index: u64,
        task_k_end: String,
        task_k_plus_1_index: u64,
        task_k_plus_1_start: String,
    },
}

impl std::fmt::Display for ContinuityFailure {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FirstTaskDoesNotMatchInitial {
                initial_head_t_hex,
                first_task_start,
            } => write!(
                f,
                "first task start_head={first_task_start} does not match \
                 manifest initial_head_t_hex={initial_head_t_hex}"
            ),
            Self::Gap {
                at_pair_index,
                task_k_index,
                task_k_end,
                task_k_plus_1_index,
                task_k_plus_1_start,
            } => write!(
                f,
                "gap at pair {at_pair_index}: task[{task_k_index}].end_head={task_k_end} \
                 != task[{task_k_plus_1_index}].start_head={task_k_plus_1_start}"
            ),
        }
    }
}

impl std::error::Error for ContinuityFailure {}

/// TRACE_MATRIX § 3 orphan (TB-G G1.2-4 2026-05-11; Option B+ §3.3):
/// CAS-anchor write. Encodes the manifest as canonical JSON bytes and
/// stores them as `ObjectType::Generic` with
/// `schema_id = "batch_continuation_manifest_g1_2_v1"`. Returns the
/// content-addressed `Cid` so callers can record it in a
/// `BatchSummaryTx` / `TerminalSummaryTx` extension field (forward
/// step; G1.2-4 does not itself emit any tx).
pub fn write_to_cas(
    manifest: &BatchContinuationManifest,
    cas: &mut CasStore,
    creator: &str,
    created_at_logical_t: u64,
) -> Result<Cid, CasError> {
    let bytes = serde_json::to_vec(manifest).map_err(|e| {
        CasError::BackendCorruption(format!("batch_continuation_manifest encode: {e}"))
    })?;
    cas.put(
        &bytes,
        ObjectType::Generic,
        creator,
        created_at_logical_t,
        Some("batch_continuation_manifest_g1_2_v1".to_string()),
    )
}

/// TRACE_MATRIX § 3 orphan (TB-G G1.2-4 2026-05-11; Option B+ §3.3):
/// cross-check helper that re-reads the live chain head from
/// `runtime_repo` and verifies the manifest's `tasks.last().end_head_t_hex`
/// matches. Used by SG-G1.2-4.4
/// (`manifest_replay_matches_real_chain_head_walk`) and by post-batch
/// audit tools.
pub fn replay_matches_real_chain_head(
    manifest: &BatchContinuationManifest,
    runtime_repo: &Path,
) -> Result<(), ReplayMismatch> {
    let writer = Git2LedgerWriter::open(runtime_repo)
        .map_err(|e| ReplayMismatch::LedgerOpen(format!("{e}")))?;
    let live_head_hex = writer.head_commit_oid_hex().unwrap_or_default();
    let live_len = writer.len();

    if manifest.tasks.is_empty() {
        // An empty batch is degenerate but not necessarily wrong —
        // only fail if the chain has progressed.
        if !live_head_hex.is_empty() {
            return Err(ReplayMismatch::EmptyManifestButNonEmptyChain { live_head_hex });
        }
        return Ok(());
    }

    let last = manifest.tasks.last().expect("non-empty");
    if last.end_head_t_hex != live_head_hex {
        return Err(ReplayMismatch::HeadMismatch {
            manifest_last_end: last.end_head_t_hex.clone(),
            live_head_hex,
        });
    }
    if last.end_chain_length != live_len {
        return Err(ReplayMismatch::ChainLengthMismatch {
            manifest_last_length: last.end_chain_length,
            live_length: live_len,
        });
    }
    Ok(())
}

/// TRACE_MATRIX § 3 orphan (TB-G G1.2-4 2026-05-11; Option B+ §3.3):
/// replay-mismatch carrier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ReplayMismatch {
    LedgerOpen(String),
    EmptyManifestButNonEmptyChain {
        live_head_hex: String,
    },
    HeadMismatch {
        manifest_last_end: String,
        live_head_hex: String,
    },
    ChainLengthMismatch {
        manifest_last_length: u64,
        live_length: u64,
    },
}

impl std::fmt::Display for ReplayMismatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::LedgerOpen(s) => write!(f, "ledger open failed: {s}"),
            Self::EmptyManifestButNonEmptyChain { live_head_hex } => write!(
                f,
                "manifest has zero tasks but live chain head is {live_head_hex}"
            ),
            Self::HeadMismatch {
                manifest_last_end,
                live_head_hex,
            } => write!(
                f,
                "manifest last end_head_t={manifest_last_end} != live chain head={live_head_hex}"
            ),
            Self::ChainLengthMismatch {
                manifest_last_length,
                live_length,
            } => write!(
                f,
                "manifest last end_chain_length={manifest_last_length} != live len={live_length}"
            ),
        }
    }
}

impl std::error::Error for ReplayMismatch {}

#[cfg(test)]
mod tests {
    use super::*;

    fn mk_entry(
        idx: u64,
        start: &str,
        end: &str,
        start_len: u64,
        end_len: u64,
    ) -> TaskContinuationEntry {
        TaskContinuationEntry {
            task_index: idx,
            problem_id: format!("p{idx}"),
            start_head_t_hex: start.into(),
            end_head_t_hex: end.into(),
            start_chain_length: start_len,
            end_chain_length: end_len,
            subprocess_command_sha256: String::new(),
            run_summary_cid_hex: None,
            terminal_tx_id: None,
            exit_code: 0,
            started_at_unix_s: 0,
            finished_at_unix_s: 0,
        }
    }

    #[test]
    fn unit_replay_continuity_accepts_continuous_chain() {
        let m = BatchContinuationManifest {
            schema_version: "g1_2_v1".into(),
            batch_id: "b".into(),
            runtime_repo: ".".into(),
            cas_root: ".".into(),
            model: "test".into(),
            n_agents: 1,
            initial_head_t_hex: String::new(),
            agent_registry_cid_hex: None,
            system_pubkeys_cid_hex: None,
            model_manifest_cid_hex: None,
            role_assignment_manifest_cid_hex: None,
            tasks: vec![
                mk_entry(0, "", "headA", 0, 1),
                mk_entry(1, "headA", "headB", 1, 2),
            ],
            terminated_reason: None,
        };
        replay_continuity(&m).expect("continuous chain accepted");
    }

    #[test]
    fn unit_replay_continuity_catches_first_task_mismatch() {
        let m = BatchContinuationManifest {
            schema_version: "g1_2_v1".into(),
            batch_id: "b".into(),
            runtime_repo: ".".into(),
            cas_root: ".".into(),
            model: "test".into(),
            n_agents: 1,
            initial_head_t_hex: "expected_genesis".into(),
            agent_registry_cid_hex: None,
            system_pubkeys_cid_hex: None,
            model_manifest_cid_hex: None,
            role_assignment_manifest_cid_hex: None,
            tasks: vec![mk_entry(0, "different_genesis", "headA", 0, 1)],
            terminated_reason: None,
        };
        match replay_continuity(&m) {
            Err(ContinuityFailure::FirstTaskDoesNotMatchInitial { .. }) => {}
            other => panic!("expected FirstTaskDoesNotMatchInitial, got {other:?}"),
        }
    }
}
