//! TB-14 Atom 2 — PriceIndex v0 derived view.
//!
//! TRACE_MATRIX FC3-N42 (architect 2026-05-03 ruling §5.1 + §5.2 + §5.4 +
//! charter §1 goal): pure deterministic function over canonical
//! `EconomicState` that derives `NodeMarketEntry` per `TxId` from
//! `node_positions_t` (TB-12 substrate) plus `conditional_share_balances_t`
//! (TB-13 substrate). **Price is signal, not truth** (architect §5.1):
//! the derived view is read-only broadcast input to the scheduler mask
//! (FR-14.5 / FR-14.6) and dashboard render (SG-14.6); it MUST NOT
//! influence predicate gates (CR-14.1 / halt-trigger #1) or L4 / L4.E
//! decision (CR-14.2 / halt-trigger #2).
//!
//! All arithmetic is integer-rational (`u128` numerator + denominator).
//! Decimal-float types are forbidden in this module per charter §5
//! Forbidden list and halt-trigger #4. Replay-deterministic per
//! Art.0.2: no env input, no clock, no randomness.

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};

use crate::economy::money::MicroCoin;
use crate::state::q_state::{AgentId, ChallengeStatus, EconomicState, ShareSidePair};
use crate::state::typed_tx::{EventId, NodePosition, PositionSide, ShareAmount};
use crate::state::{TaskId, TxId};

// ─────────────────────────────────────────────────────────────────────────
// CanonicalNodeGraph — TB-14 Atom 6 B′ step 4 (architect ruling 2026-05-03 §3+§4)
// ─────────────────────────────────────────────────────────────────────────

/// TRACE_MATRIX TB-14 Atom 6 B′ step 4 (FC2-N28; architect ruling 2026-05-03
/// §3+§4): canonical-keyed parent → children edge map. Replaces the legacy
/// shadow `kernel.tape` consumption in `compute_mask_set` exposed by Codex
/// R1 ship audit VETO.
///
/// **Keys**: canonical accepted `WorkTx.tx_id` (NOT shadow
/// `tx_{count}_by_{author}` ids generated by `bus.append`). Parents and
/// children are both canonical TxIds, so `compute_mask_set` operates in
/// the same id namespace as `compute_price_index` (architect §3
/// canonical namespace decision).
///
/// **Construction**: derived from L4 accepted WorkTx + CAS-resident
/// `ProposalTelemetry.parent_tx` (linked via `WorkTx.proposal_cid`) at
/// bus snapshot time. See `Sequencer::compute_canonical_edges_at_head`
/// for the canonical builder.
///
/// **Replay determinism** (Art.0.2): L4 chain + CAS payloads are both
/// replay-deterministic by TB-13 chaintape evidence. Walking L4 in order
/// + reading ProposalTelemetry from CAS yields a byte-equal map across
/// live vs replay.
///
/// **Empty fallback**: when bus runs sequencer-less (legacy WAL-only
/// mode), the graph is empty `BTreeMap::new()`. `compute_mask_set` over
/// an empty graph returns an empty mask — no parents have children to
/// dominate them. Consumers (evaluator / dashboard) treat empty as "no
/// canonical edges yet" without crashing.
pub type CanonicalNodeGraph = BTreeMap<TxId, BTreeSet<TxId>>;

// ─────────────────────────────────────────────────────────────────────────
// RationalPrice — architect §5.2 verbatim shape
// ─────────────────────────────────────────────────────────────────────────

/// TRACE_MATRIX TB-14 Atom 2 (architect §5.2 verbatim): integer-rational
/// price representation. `numerator / denominator` ∈ \[0, 1\] when
/// constructed by `compute_price_index` (architect FR-14.1 + FR-14.2). All
/// comparisons use cross-multiplication; no division until the dashboard
/// render layer (SG-14.6) where it is purely cosmetic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct RationalPrice {
    pub numerator: u128,
    pub denominator: u128,
}

impl RationalPrice {
    /// TRACE_MATRIX FC3-N42 (architect §5.5 SG-14.x mask-margin gate; helper
    /// for FC2-N28 `compute_mask_set` in Atom 3): cross-multiplication
    /// dominance predicate.
    ///
    /// True iff `self - other >= margin`, computed by cross-multiplication
    /// to avoid division. Used by Atom 3's `compute_mask_set` to enforce
    /// the price-margin gate (FR-14.5 / SG-14.x). Defensive: returns
    /// `false` on any zero denominator (`compute_price_index` never
    /// produces a `RationalPrice` with zero denominator — that case is
    /// `Option::None` per FR-14.3 / halt-trigger #5 — but defense-in-depth
    /// is cheap).
    pub fn dominates_by(&self, other: &RationalPrice, margin: &RationalPrice) -> bool {
        if self.denominator == 0 || other.denominator == 0 || margin.denominator == 0 {
            return false;
        }
        // Goal: self - other >= margin
        //   (self.n * other.d - other.n * self.d) / (self.d * other.d)
        //       >= margin.n / margin.d
        // Cross-multiply by (self.d * other.d * margin.d) > 0:
        //   (self.n * other.d - other.n * self.d) * margin.d
        //       >= margin.n * (self.d * other.d)
        let self_d = self.denominator;
        let other_d = other.denominator;
        let cross_diff = self
            .numerator
            .saturating_mul(other_d)
            .saturating_sub(other.numerator.saturating_mul(self_d));
        let lhs = cross_diff.saturating_mul(margin.denominator);
        let rhs = margin
            .numerator
            .saturating_mul(self_d)
            .saturating_mul(other_d);
        lhs >= rhs
    }
}

// ─────────────────────────────────────────────────────────────────────────
// NodeMarketEntry — architect §5.2 verbatim shape (10 fields)
// ─────────────────────────────────────────────────────────────────────────

/// TRACE_MATRIX TB-14 Atom 2 (architect §5.2 verbatim): per-node market
/// signal entry. **Derived view** populated by `compute_price_index`;
/// never stored as canonical state (architect §5.1: "price is signal,
/// not truth"; charter §7 auto-resolution A: "no second source-of-truth").
///
/// Field semantics:
/// - `node_id` — the `TxId` of the WorkTx attempt-node these positions reference
/// - `task_id` — the `TaskId` (Q-derived from any underlying `NodePosition`)
/// - `event_id` — `EventId(task_id)` (TB-13: 1:1 with TaskId per `typed_tx.rs:1075`)
/// - `long_interest` / `short_interest` — sum of `NodePosition.amount` per side
/// - `yes_share_depth` / `no_share_depth` — sum of `ConditionalShareBalances` for `event_id`
/// - `price_yes` / `price_no` — `Option<RationalPrice>`; `None` iff zero liquidity (FR-14.3)
/// - `liquidity_depth` — `long_interest + short_interest` (saturating)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct NodeMarketEntry {
    pub node_id: TxId,
    pub task_id: TaskId,
    pub event_id: EventId,
    pub long_interest: MicroCoin,
    pub short_interest: MicroCoin,
    pub yes_share_depth: ShareAmount,
    pub no_share_depth: ShareAmount,
    pub price_yes: Option<RationalPrice>,
    pub price_no: Option<RationalPrice>,
    pub liquidity_depth: MicroCoin,
}

// ─────────────────────────────────────────────────────────────────────────
// compute_price_index — pure fn over EconomicState
// ─────────────────────────────────────────────────────────────────────────

/// TRACE_MATRIX TB-14 Atom 2 (FC3-N42; architect §5.1 + charter §3 Atom 2):
/// derive the per-node `PriceIndex` from `EconomicState.node_positions_t`
/// (long / short interest aggregation; FR-14.1 / FR-14.2) and
/// `conditional_share_balances_t` (yes / no share depth aggregation per
/// `event_id`).
///
/// **Replay-deterministic** (Art.0.2): pure over the canonical state
/// vector; no env / clock / RNG. Iteration order is `BTreeMap` order on
/// `TxId`, which is lexicographic on the inner `String`.
///
/// **No predicate side-effect** (CR-14.1 / halt-trigger #1): this is a
/// read-only derivation; the sequencer never reads its result during
/// `dispatch_transition` (predicate gate at `sequencer.rs:516-558`).
///
/// **Empty / zero-stake → None** (FR-14.3 / halt-trigger #5): a node with
/// zero long AND zero short interest yields
/// `price_yes == None && price_no == None`. Rationale: division-by-zero
/// avoidance and architect §5.7 halt trigger 5.
pub fn compute_price_index(econ: &EconomicState) -> BTreeMap<TxId, NodeMarketEntry> {
    // Pass 1: group NodePositions by node_id; collect (task_id, long_micro, short_micro).
    let mut groups: BTreeMap<TxId, (TaskId, u128, u128)> = BTreeMap::new();
    for position in econ.node_positions_t.0.values() {
        let amount_micro = position.amount.micro_units();
        let amount_u128 = if amount_micro < 0 {
            0u128
        } else {
            amount_micro as u128
        };
        let entry = groups
            .entry(position.node_id.clone())
            .or_insert_with(|| (position.task_id.clone(), 0u128, 0u128));
        match position.side {
            PositionSide::Long => entry.1 = entry.1.saturating_add(amount_u128),
            PositionSide::Short => entry.2 = entry.2.saturating_add(amount_u128),
        }
    }

    // Pass 2: per node, derive NodeMarketEntry.
    let mut out: BTreeMap<TxId, NodeMarketEntry> = BTreeMap::new();
    for (node_id, (task_id, long_micro, short_micro)) in groups.into_iter() {
        let total_micro = long_micro.saturating_add(short_micro);
        let event_id = EventId(task_id.clone());

        let to_micro = |u: u128| -> MicroCoin {
            // Saturating cast u128 → i64 (positive values only; cap at i64::MAX).
            let capped = if u > i64::MAX as u128 {
                i64::MAX
            } else {
                u as i64
            };
            MicroCoin::from_micro_units(capped)
        };

        let (price_yes, price_no) = if total_micro == 0 {
            (None, None)
        } else {
            (
                Some(RationalPrice {
                    numerator: long_micro,
                    denominator: total_micro,
                }),
                Some(RationalPrice {
                    numerator: short_micro,
                    denominator: total_micro,
                }),
            )
        };

        // yes_share_depth / no_share_depth: sum across all owners' balances
        // for this event_id. The conditional_share_balances_t shape is
        // `BTreeMap<AgentId, BTreeMap<EventId, ShareSidePair>>`.
        let mut yes_share_total: u128 = 0;
        let mut no_share_total: u128 = 0;
        for owner_map in econ.conditional_share_balances_t.0.values() {
            if let Some(pair) = owner_map.get(&event_id) {
                yes_share_total = yes_share_total.saturating_add(pair.yes.units);
                no_share_total = no_share_total.saturating_add(pair.no.units);
            }
        }

        out.insert(
            node_id.clone(),
            NodeMarketEntry {
                node_id,
                task_id,
                event_id,
                long_interest: to_micro(long_micro),
                short_interest: to_micro(short_micro),
                yes_share_depth: ShareAmount::from_units(yes_share_total),
                no_share_depth: ShareAmount::from_units(no_share_total),
                price_yes,
                price_no,
                liquidity_depth: to_micro(total_micro),
            },
        );
    }

    out
}

// ─────────────────────────────────────────────────────────────────────────
// BoltzmannMaskPolicy — architect §5.2 verbatim shape (skeleton in Atom 3;
// `from_env()` constructor lands in Atom 4 per charter §3 split).
// ─────────────────────────────────────────────────────────────────────────

/// TRACE_MATRIX TB-14 Atom 3 (architect §5.2 verbatim; FC2-N28 + FC2-N29
/// configuration carrier): integer-rational policy parameters for the
/// Boltzmann scheduler mask + epsilon-greedy exploration + price-margin
/// gate. **Atom 3 ships the data shape only**; `from_env()` env-var
/// loader lands in Atom 4 per charter §3 (separate iter-cap tracking).
///
/// Field semantics:
/// - `beta_num` / `beta_den` — rational temperature for argmax tiebreaking
///   (Atom 5 boltzmann_select_parent_v2 uses these). Default = 1/1.
/// - `min_liquidity` — `child.liquidity_depth` floor below which child
///   cannot mask parent (CR-14.4). Default = 1 Coin (1_000_000 micro).
/// - `price_margin` — minimum dominance gap for child to mask parent
///   (FR-14.5 / SG-14.x). Default = 1/10 (10% margin).
/// - `epsilon_exploration_num` / `epsilon_exploration_den` — random
///   exploration probability in argmax + epsilon-greedy (SG-14.5).
///   Default = 1/10 (10% exploration).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BoltzmannMaskPolicy {
    pub beta_num: i64,
    pub beta_den: i64,
    pub min_liquidity: MicroCoin,
    pub price_margin: RationalPrice,
    pub epsilon_exploration_num: u64,
    pub epsilon_exploration_den: u64,
}

impl Default for BoltzmannMaskPolicy {
    fn default() -> Self {
        Self {
            beta_num: 1,
            beta_den: 1,
            min_liquidity: MicroCoin::from_micro_units(1_000_000),
            price_margin: RationalPrice {
                numerator: 1,
                denominator: 10,
            },
            epsilon_exploration_num: 1,
            epsilon_exploration_den: 10,
        }
    }
}

impl BoltzmannMaskPolicy {
    /// TRACE_MATRIX TB-14 Atom 4 (FC2-N28 + FC2-N29 configuration loader;
    /// charter §3 Atom 4): build a policy from process environment with
    /// per-field defaults matching `BoltzmannMaskPolicy::default()`.
    ///
    /// **All 7 fields are integer-rational** (architect §5.6 forbidden:
    /// no decimal float anywhere in the policy surface). The seven env
    /// vars are: `BOLTZMANN_BETA_NUM` / `BOLTZMANN_BETA_DEN`,
    /// `BOLTZMANN_MIN_LIQUIDITY_MICRO`, `BOLTZMANN_PRICE_MARGIN_NUM` /
    /// `BOLTZMANN_PRICE_MARGIN_DEN`, `BOLTZMANN_EPSILON_NUM` /
    /// `BOLTZMANN_EPSILON_DEN`. Unparsable values silently fall back to
    /// the field default — fail-soft is the right policy for a scheduler
    /// hyperparameter loader (Art.I.1 + C-027: env-overridable, never
    /// hardcoded; misconfiguration must not crash the swarm).
    ///
    /// **Determinism note**: this function reads `std::env::var` and is
    /// therefore NOT replay-deterministic by itself. Production callers
    /// (Atom 6 evaluator wire-up) load the policy ONCE at run start, then
    /// pass it as an explicit input to `compute_mask_set` /
    /// `boltzmann_select_parent_v2`, which ARE deterministic given the
    /// fixed policy. This separation preserves Art.0.2 replay-determinism
    /// at the deterministic boundary while allowing operational tuning at
    /// the env-var boundary.
    pub fn from_env() -> Self {
        let default = Self::default();

        fn parse_i64(key: &str, fallback: i64) -> i64 {
            std::env::var(key)
                .ok()
                .and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(fallback)
        }
        fn parse_u64(key: &str, fallback: u64) -> u64 {
            std::env::var(key)
                .ok()
                .and_then(|s| s.parse::<u64>().ok())
                .unwrap_or(fallback)
        }
        fn parse_u128(key: &str, fallback: u128) -> u128 {
            std::env::var(key)
                .ok()
                .and_then(|s| s.parse::<u128>().ok())
                .unwrap_or(fallback)
        }

        // TB-14 Atom 6 follow-up (architect ruling 2026-05-03 step 2):
        // env-load validation for production safety. Per Codex R1 secondary
        // CHALLENGE — `from_env` previously accepted nonsensical values
        // (negative `min_liquidity` flowing into MicroCoin; zero
        // `price_margin` denominator interacting with saturating_sub in
        // dominates_by). Rule per architect ruling:
        //   - min_liquidity > 0           (non-positive → fall back to default)
        //   - price_margin > 0            (zero numerator OR zero denominator → default)
        //   - beta_den > 0                (zero → default; argmax tiebreaker)
        //   - beta_num >= 0               (negative → default)
        //   - epsilon in [0, 1]           (num > den → default; den=0 also → default)
        //
        // Fail-soft policy unchanged (Art.I.1 + C-027): a misconfigured
        // env var falls back to `Default::default()` for THAT FIELD.
        // Misconfiguration must not crash the swarm; production semantics
        // must remain inside the architect-mandated invariant envelope.
        let beta_num_raw = parse_i64("BOLTZMANN_BETA_NUM", default.beta_num);
        let beta_num = if beta_num_raw >= 0 {
            beta_num_raw
        } else {
            default.beta_num
        };
        let beta_den_raw = parse_i64("BOLTZMANN_BETA_DEN", default.beta_den);
        let beta_den = if beta_den_raw > 0 {
            beta_den_raw
        } else {
            default.beta_den
        };

        let min_liq_raw = parse_i64(
            "BOLTZMANN_MIN_LIQUIDITY_MICRO",
            default.min_liquidity.micro_units(),
        );
        let min_liquidity = if min_liq_raw > 0 {
            MicroCoin::from_micro_units(min_liq_raw)
        } else {
            default.min_liquidity
        };

        let pm_num = parse_u128("BOLTZMANN_PRICE_MARGIN_NUM", default.price_margin.numerator);
        let pm_den = parse_u128(
            "BOLTZMANN_PRICE_MARGIN_DEN",
            default.price_margin.denominator,
        );
        let price_margin = if pm_num > 0 && pm_den > 0 {
            RationalPrice {
                numerator: pm_num,
                denominator: pm_den,
            }
        } else {
            default.price_margin
        };

        let eps_num = parse_u64("BOLTZMANN_EPSILON_NUM", default.epsilon_exploration_num);
        let eps_den = parse_u64("BOLTZMANN_EPSILON_DEN", default.epsilon_exploration_den);
        // epsilon ∈ [0, 1] interpreted as eps_num / eps_den ∈ [0, 1].
        // den must be > 0; num must be ≤ den (epsilon ≤ 1; epsilon = 0 is
        // the "no exploration" boundary and is accepted).
        let (epsilon_exploration_num, epsilon_exploration_den) =
            if eps_den > 0 && eps_num <= eps_den {
                (eps_num, eps_den)
            } else {
                (
                    default.epsilon_exploration_num,
                    default.epsilon_exploration_den,
                )
            };

        Self {
            beta_num,
            beta_den,
            min_liquidity,
            price_margin,
            epsilon_exploration_num,
            epsilon_exploration_den,
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────
// compute_mask_set — derive the parent-mask set from price_index +
// CanonicalNodeGraph + policy + open challenges. Pure over inputs.
// ─────────────────────────────────────────────────────────────────────────

/// TRACE_MATRIX TB-14 Atom 3 (FC2-N28; architect §5.5 SG-14.3 / SG-14.5 /
/// SG-14.7 / SG-14.8 + charter §3 Atom 3); rewired in Atom 6 B′ step 4
/// (architect ruling 2026-05-03 §3+§4) to consume `CanonicalNodeGraph`
/// in place of the legacy shadow `kernel.tape`: derive the per-round
/// `mask_set: BTreeSet<TxId>` of parent-attempt-nodes whose visibility
/// is suppressed in the agent read-view because they are dominated by a
/// child whose YES-price exceeds the parent's by `policy.price_margin`.
///
/// **Read-view mask, not deletion** (CR-14.3 + SG-14.3 + halt-trigger #3):
/// the canonical L4 chain itself is unchanged; this function only
/// nominates parent IDs for filtering at the scheduler / read-view
/// boundary. The full L4 + canonical edge map iteration always yields
/// masked parents.
///
/// **Algorithm** (architect §5.5 + charter §3 Atom 3):
/// for each `(parent_id, parent_entry)` in `price_index`:
///   for each `child_id` in `edges.get(parent_id)` (canonical-graph children):
///     - if `child.liquidity_depth < policy.min_liquidity`: skip (CR-14.4 / SG-14.8)
///     - if any `ChallengeCase` targets `child_id` with status `Open`:
///       skip (CR-14.5 / SG-14.7 / halt-trigger #6)
///     - if `child.price_yes >= parent.price_yes + policy.price_margin`
///       (cross-multiplication; no division): insert `parent_id` and
///       move on to next parent (one dominating child suffices).
///
/// **Determinism**: `BTreeMap` / `BTreeSet` ordering on `TxId` (lexicographic
/// on inner `String`); canonical-graph children iteration is in BTreeSet
/// order; output `BTreeSet` is therefore deterministic given identical inputs.
///
/// **Returns parent IDs only**, not (parent, child) edges; the mask is a
/// flat set per FR-14.5 + charter §7 auto-resolution B (global v0).
///
/// **TB-14 Atom 6 B′ step 4 (architect ruling 2026-05-03 §3+§4)**: this
/// function NO LONGER reads the shadow `kernel.tape`. The parent → children
/// edges come from a `CanonicalNodeGraph` keyed by canonical
/// `WorkTx.tx_id`, derived from L4 + ProposalTelemetry.parent_tx at bus
/// snapshot time. The shadow Tape (used pre-Atom-6 by the legacy CPMM
/// read-view) lived in a different id namespace and produced empty mask_set
/// in production (Codex R1 ship audit VETO). The canonical-graph rewire
/// closes that gap.
pub fn compute_mask_set(
    econ: &EconomicState,
    edges: &CanonicalNodeGraph,
    policy: &BoltzmannMaskPolicy,
    price_index: &BTreeMap<TxId, NodeMarketEntry>,
) -> BTreeSet<TxId> {
    let mut mask: BTreeSet<TxId> = BTreeSet::new();

    // Build a quick lookup: child_node_id → has any Open challenge targeting it?
    // ChallengeCasesIndex shape: BTreeMap<TxId (challenge_id), ChallengeCase>.
    // Each ChallengeCase has target_work_tx + status. We index by target_work_tx
    // and treat Open as the only blocking status (Released / UpheldDeferred
    // are resolved per CR-14.5 + SG-14.7 — those do not block masking).
    let mut open_challenge_targets: BTreeSet<&TxId> = BTreeSet::new();
    for case in econ.challenge_cases_t.0.values() {
        if case.status == ChallengeStatus::Open {
            open_challenge_targets.insert(&case.target_work_tx);
        }
    }

    for (parent_id, parent_entry) in price_index.iter() {
        // Parent without YES price is uninformative (zero-liquidity per
        // FR-14.3); cannot be dominated by any child via price_margin.
        let parent_price_yes = match parent_entry.price_yes.as_ref() {
            Some(p) => p,
            None => continue,
        };

        // Look up children via canonical-graph parent-edges (architect ruling
        // 2026-05-03 §3+§4: replaces shadow `tape.children` consumption).
        let children_set = match edges.get(parent_id) {
            Some(s) => s,
            None => continue,
        };
        for child_tx_id in children_set.iter() {
            // Look up child's NodeMarketEntry.
            let child_entry = match price_index.get(child_tx_id) {
                Some(e) => e,
                None => continue,
            };

            // CR-14.4 / SG-14.8: low-liquidity children cannot mask parent.
            if child_entry.liquidity_depth.micro_units() < policy.min_liquidity.micro_units() {
                continue;
            }

            // CR-14.5 / SG-14.7 / halt-trigger #6: open challenge blocks masking.
            if open_challenge_targets.contains(child_tx_id) {
                continue;
            }

            // FR-14.5 dominance check: child.price_yes >= parent.price_yes
            // + price_margin (computed via cross-multiplication; no division).
            let child_price_yes = match child_entry.price_yes.as_ref() {
                Some(p) => p,
                None => continue,
            };

            if child_price_yes.dominates_by(parent_price_yes, &policy.price_margin) {
                mask.insert(parent_id.clone());
                break; // One dominating child suffices.
            }
        }
    }

    mask
}

// ─────────────────────────────────────────────────────────────────────────
// Inline unit tests — pure-fn coverage of FR-14.1..3 + determinism +
// rational-equality invariant. The decimal-float fence test lives in
// `tests/tb_14_halt_triggers.rs` (halt-trigger #4); this module never
// reads its own source.
// ─────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::typed_tx::PositionKind;
    use std::collections::BTreeMap as Map;

    fn micro(units: i64) -> MicroCoin {
        MicroCoin::from_micro_units(units)
    }

    fn make_position(
        position_id: &str,
        node_id: &str,
        task_id: &str,
        owner: &str,
        side: PositionSide,
        kind: PositionKind,
        amount_micro: i64,
    ) -> NodePosition {
        NodePosition {
            position_id: TxId(position_id.into()),
            node_id: TxId(node_id.into()),
            task_id: TaskId(task_id.into()),
            owner: AgentId(owner.into()),
            side,
            kind,
            amount: micro(amount_micro),
            source_tx: TxId(position_id.into()),
            opened_at_round: 1,
        }
    }

    fn econ_with_positions(positions: Vec<NodePosition>) -> EconomicState {
        let mut econ = EconomicState::default();
        for p in positions {
            econ.node_positions_t.0.insert(p.position_id.clone(), p);
        }
        econ
    }

    #[test]
    fn empty_state_yields_empty_index() {
        let econ = EconomicState::default();
        let idx = compute_price_index(&econ);
        assert!(idx.is_empty(), "empty positions → empty PriceIndex");
    }

    #[test]
    fn single_long_position_yields_price_yes_full() {
        // FR-14.1: price_yes = long / (long + short).
        let econ = econ_with_positions(vec![make_position(
            "p1",
            "n1",
            "t1",
            "a1",
            PositionSide::Long,
            PositionKind::FirstLong,
            500_000,
        )]);
        let idx = compute_price_index(&econ);
        let entry = idx.get(&TxId("n1".into())).expect("n1 present");
        assert_eq!(
            entry.price_yes,
            Some(RationalPrice {
                numerator: 500_000,
                denominator: 500_000
            })
        );
        assert_eq!(
            entry.price_no,
            Some(RationalPrice {
                numerator: 0,
                denominator: 500_000
            })
        );
        assert_eq!(entry.long_interest, micro(500_000));
        assert_eq!(entry.short_interest, MicroCoin::zero());
        assert_eq!(entry.liquidity_depth, micro(500_000));
        assert_eq!(entry.task_id, TaskId("t1".into()));
        assert_eq!(entry.event_id, EventId(TaskId("t1".into())));
    }

    #[test]
    fn single_short_position_yields_price_no_full() {
        // FR-14.2: price_no = short / (long + short).
        let econ = econ_with_positions(vec![make_position(
            "p1",
            "n1",
            "t1",
            "a1",
            PositionSide::Short,
            PositionKind::ChallengeShort,
            300_000,
        )]);
        let idx = compute_price_index(&econ);
        let entry = idx.get(&TxId("n1".into())).expect("n1 present");
        assert_eq!(
            entry.price_no,
            Some(RationalPrice {
                numerator: 300_000,
                denominator: 300_000
            })
        );
        assert_eq!(
            entry.price_yes,
            Some(RationalPrice {
                numerator: 0,
                denominator: 300_000
            })
        );
    }

    #[test]
    fn equal_long_short_yields_half_each() {
        let econ = econ_with_positions(vec![
            make_position(
                "p1",
                "n1",
                "t1",
                "a1",
                PositionSide::Long,
                PositionKind::FirstLong,
                400_000,
            ),
            make_position(
                "p2",
                "n1",
                "t1",
                "a2",
                PositionSide::Short,
                PositionKind::ChallengeShort,
                400_000,
            ),
        ]);
        let idx = compute_price_index(&econ);
        let entry = idx.get(&TxId("n1".into())).expect("n1 present");
        assert_eq!(
            entry.price_yes,
            Some(RationalPrice {
                numerator: 400_000,
                denominator: 800_000
            })
        );
        assert_eq!(
            entry.price_no,
            Some(RationalPrice {
                numerator: 400_000,
                denominator: 800_000
            })
        );
    }

    #[test]
    fn rational_equality_invariant() {
        // For any non-zero-liquidity node:
        //   price_yes.num + price_no.num == price_yes.den == price_no.den.
        let econ = econ_with_positions(vec![
            make_position(
                "p1",
                "n1",
                "t1",
                "a1",
                PositionSide::Long,
                PositionKind::FirstLong,
                700_000,
            ),
            make_position(
                "p2",
                "n1",
                "t1",
                "a2",
                PositionSide::Short,
                PositionKind::ChallengeShort,
                300_000,
            ),
        ]);
        let idx = compute_price_index(&econ);
        let entry = idx.get(&TxId("n1".into())).expect("n1 present");
        let py = entry.price_yes.expect("price_yes present");
        let pn = entry.price_no.expect("price_no present");
        assert_eq!(py.denominator, pn.denominator, "denominators must match");
        assert_eq!(
            py.numerator + pn.numerator,
            py.denominator,
            "rational equality: long_n + short_n == total"
        );
    }

    #[test]
    fn determinism_n_calls_identical() {
        let econ = econ_with_positions(vec![
            make_position(
                "p1",
                "n1",
                "t1",
                "a1",
                PositionSide::Long,
                PositionKind::FirstLong,
                700_000,
            ),
            make_position(
                "p2",
                "n2",
                "t2",
                "a2",
                PositionSide::Short,
                PositionKind::ChallengeShort,
                300_000,
            ),
            make_position(
                "p3",
                "n1",
                "t1",
                "a3",
                PositionSide::Short,
                PositionKind::ChallengeShort,
                100_000,
            ),
        ]);
        let first = compute_price_index(&econ);
        for _ in 0..10 {
            assert_eq!(
                compute_price_index(&econ),
                first,
                "deterministic across calls"
            );
        }
    }

    #[test]
    fn yes_share_depth_aggregates_across_owners() {
        use crate::state::typed_tx::EventId;
        // Two owners hold YES/NO shares for event_id=task_x; depths sum.
        let mut econ = econ_with_positions(vec![make_position(
            "p1",
            "node_x",
            "task_x",
            "a1",
            PositionSide::Long,
            PositionKind::FirstLong,
            100_000,
        )]);
        let event_id = EventId(TaskId("task_x".into()));
        let mut a1_map: Map<EventId, ShareSidePair> = Map::new();
        a1_map.insert(
            event_id.clone(),
            ShareSidePair {
                yes: ShareAmount::from_units(50_000),
                no: ShareAmount::from_units(20_000),
            },
        );
        let mut a2_map: Map<EventId, ShareSidePair> = Map::new();
        a2_map.insert(
            event_id.clone(),
            ShareSidePair {
                yes: ShareAmount::from_units(70_000),
                no: ShareAmount::from_units(30_000),
            },
        );
        econ.conditional_share_balances_t
            .0
            .insert(AgentId("a1".into()), a1_map);
        econ.conditional_share_balances_t
            .0
            .insert(AgentId("a2".into()), a2_map);

        let idx = compute_price_index(&econ);
        let entry = idx.get(&TxId("node_x".into())).expect("node_x present");
        assert_eq!(entry.yes_share_depth, ShareAmount::from_units(120_000));
        assert_eq!(entry.no_share_depth, ShareAmount::from_units(50_000));
    }

    #[test]
    fn rational_dominates_by() {
        // 0.60 - 0.40 = 0.20 >= 0.10 ✓
        let p60 = RationalPrice {
            numerator: 60,
            denominator: 100,
        };
        let p40 = RationalPrice {
            numerator: 40,
            denominator: 100,
        };
        let m10 = RationalPrice {
            numerator: 1,
            denominator: 10,
        };
        assert!(p60.dominates_by(&p40, &m10));
        assert!(!p40.dominates_by(&p60, &m10));
        // 0.60 vs 0.50 by 0.20 → does not dominate.
        let p50 = RationalPrice {
            numerator: 50,
            denominator: 100,
        };
        let m20 = RationalPrice {
            numerator: 1,
            denominator: 5,
        };
        assert!(!p60.dominates_by(&p50, &m20));
        // 0.70 vs 0.50 by 0.20 → dominates.
        let p70 = RationalPrice {
            numerator: 70,
            denominator: 100,
        };
        assert!(p70.dominates_by(&p50, &m20));
        // Defense: zero denominator returns false.
        let zero_den = RationalPrice {
            numerator: 1,
            denominator: 0,
        };
        assert!(!p60.dominates_by(&zero_den, &m10));
        assert!(!zero_den.dominates_by(&p60, &m10));
    }

    // ──────────── BoltzmannMaskPolicy::from_env (Atom 4) ────────────
    //
    // Tests mutate process-global env vars; serialize with a static Mutex
    // per `feedback_env_var_test_lock` (cargo's default test runner is
    // parallel across threads within a single test binary).

    use std::sync::Mutex;
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn with_env_isolated<F: FnOnce()>(f: F) {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let keys = [
            "BOLTZMANN_BETA_NUM",
            "BOLTZMANN_BETA_DEN",
            "BOLTZMANN_MIN_LIQUIDITY_MICRO",
            "BOLTZMANN_PRICE_MARGIN_NUM",
            "BOLTZMANN_PRICE_MARGIN_DEN",
            "BOLTZMANN_EPSILON_NUM",
            "BOLTZMANN_EPSILON_DEN",
        ];
        for k in &keys {
            std::env::remove_var(k);
        }
        f();
        for k in &keys {
            std::env::remove_var(k);
        }
    }

    #[test]
    fn boltzmann_mask_policy_default_matches_field_defaults() {
        let p = BoltzmannMaskPolicy::default();
        assert_eq!(p.beta_num, 1);
        assert_eq!(p.beta_den, 1);
        assert_eq!(p.min_liquidity, MicroCoin::from_micro_units(1_000_000));
        assert_eq!(
            p.price_margin,
            RationalPrice {
                numerator: 1,
                denominator: 10
            }
        );
        assert_eq!(p.epsilon_exploration_num, 1);
        assert_eq!(p.epsilon_exploration_den, 10);
    }

    #[test]
    fn boltzmann_from_env_with_no_vars_set_matches_default() {
        with_env_isolated(|| {
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(p, BoltzmannMaskPolicy::default());
        });
    }

    #[test]
    fn boltzmann_from_env_overrides_each_field() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_BETA_NUM", "3");
            std::env::set_var("BOLTZMANN_BETA_DEN", "2");
            std::env::set_var("BOLTZMANN_MIN_LIQUIDITY_MICRO", "5000000");
            std::env::set_var("BOLTZMANN_PRICE_MARGIN_NUM", "7");
            std::env::set_var("BOLTZMANN_PRICE_MARGIN_DEN", "20");
            std::env::set_var("BOLTZMANN_EPSILON_NUM", "3");
            std::env::set_var("BOLTZMANN_EPSILON_DEN", "100");

            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(p.beta_num, 3);
            assert_eq!(p.beta_den, 2);
            assert_eq!(p.min_liquidity, MicroCoin::from_micro_units(5_000_000));
            assert_eq!(
                p.price_margin,
                RationalPrice {
                    numerator: 7,
                    denominator: 20
                }
            );
            assert_eq!(p.epsilon_exploration_num, 3);
            assert_eq!(p.epsilon_exploration_den, 100);
        });
    }

    #[test]
    fn boltzmann_from_env_invalid_values_fall_back_to_defaults() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_BETA_NUM", "not_a_number");
            std::env::set_var("BOLTZMANN_PRICE_MARGIN_NUM", "");
            std::env::set_var("BOLTZMANN_EPSILON_NUM", "abc");
            // Other vars left unset (also fall back to default).

            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(p.beta_num, 1, "invalid value falls back to default 1");
            assert_eq!(
                p.price_margin.numerator, 1,
                "empty value falls back to default 1"
            );
            assert_eq!(
                p.epsilon_exploration_num, 1,
                "non-numeric value falls back to default 1"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_serde_round_trip() {
        let p = BoltzmannMaskPolicy {
            beta_num: 5,
            beta_den: 3,
            min_liquidity: MicroCoin::from_micro_units(7_000_000),
            price_margin: RationalPrice {
                numerator: 11,
                denominator: 13,
            },
            epsilon_exploration_num: 17,
            epsilon_exploration_den: 19,
        };
        let json = serde_json::to_string(&p).unwrap();
        let back: BoltzmannMaskPolicy = serde_json::from_str(&json).unwrap();
        assert_eq!(p, back, "serde JSON round-trip identity");
    }

    // ─── B′ step 2 (architect ruling 2026-05-03) — env validation ───────
    //
    // Per Codex R1 secondary CHALLENGE: from_env previously accepted
    // nonsensical values (negative min_liquidity, zero price_margin
    // denominator). Each test below pins the per-field validation rule:
    // invalid input falls back to the field's Default value (fail-soft;
    // misconfiguration must not crash the swarm; production semantics
    // must remain inside the architect-mandated invariant envelope).

    #[test]
    fn boltzmann_from_env_negative_min_liquidity_falls_back_to_default() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_MIN_LIQUIDITY_MICRO", "-500000");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                p.min_liquidity,
                BoltzmannMaskPolicy::default().min_liquidity,
                "negative min_liquidity must fall back to default (architect step 2: min_liquidity > 0)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_zero_min_liquidity_falls_back_to_default() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_MIN_LIQUIDITY_MICRO", "0");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                p.min_liquidity,
                BoltzmannMaskPolicy::default().min_liquidity,
                "zero min_liquidity must fall back to default (architect step 2: min_liquidity > 0; > not >=)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_zero_price_margin_denominator_falls_back_to_default() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_PRICE_MARGIN_DEN", "0");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                p.price_margin,
                BoltzmannMaskPolicy::default().price_margin,
                "zero price_margin denominator must fall back to default (architect step 2: price_margin > 0)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_zero_price_margin_numerator_falls_back_to_default() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_PRICE_MARGIN_NUM", "0");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                p.price_margin,
                BoltzmannMaskPolicy::default().price_margin,
                "zero price_margin numerator must fall back to default (architect step 2: price_margin > 0)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_zero_beta_den_falls_back_to_default() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_BETA_DEN", "0");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                p.beta_den,
                BoltzmannMaskPolicy::default().beta_den,
                "zero beta_den must fall back to default (architect step 2: beta_den > 0)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_negative_beta_num_falls_back_to_default() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_BETA_NUM", "-3");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                p.beta_num,
                BoltzmannMaskPolicy::default().beta_num,
                "negative beta_num must fall back to default (architect step 2: beta_num >= 0)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_zero_beta_num_accepted() {
        with_env_isolated(|| {
            std::env::set_var("BOLTZMANN_BETA_NUM", "0");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                p.beta_num, 0,
                "zero beta_num is INSIDE [0, ∞) range and must be accepted (architect step 2: beta_num >= 0)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_epsilon_above_one_falls_back_to_default() {
        with_env_isolated(|| {
            // epsilon = 11/10 > 1.0 → invalid → default.
            std::env::set_var("BOLTZMANN_EPSILON_NUM", "11");
            std::env::set_var("BOLTZMANN_EPSILON_DEN", "10");
            let p = BoltzmannMaskPolicy::from_env();
            let d = BoltzmannMaskPolicy::default();
            assert_eq!(
                (p.epsilon_exploration_num, p.epsilon_exploration_den),
                (d.epsilon_exploration_num, d.epsilon_exploration_den),
                "epsilon > 1 must fall back to default pair (architect step 2: epsilon ∈ [0, 1])"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_epsilon_zero_den_falls_back_to_default() {
        with_env_isolated(|| {
            // epsilon den=0 → division-by-zero risk → invalid → default.
            std::env::set_var("BOLTZMANN_EPSILON_DEN", "0");
            let p = BoltzmannMaskPolicy::from_env();
            let d = BoltzmannMaskPolicy::default();
            assert_eq!(
                (p.epsilon_exploration_num, p.epsilon_exploration_den),
                (d.epsilon_exploration_num, d.epsilon_exploration_den),
                "epsilon den=0 must fall back to default pair (architect step 2: epsilon ∈ [0, 1] requires den > 0)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_epsilon_zero_accepted() {
        with_env_isolated(|| {
            // epsilon = 0/100 = 0 is INSIDE [0, 1] (no exploration) → accepted.
            std::env::set_var("BOLTZMANN_EPSILON_NUM", "0");
            std::env::set_var("BOLTZMANN_EPSILON_DEN", "100");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                (p.epsilon_exploration_num, p.epsilon_exploration_den),
                (0, 100),
                "epsilon = 0 is inside [0, 1] and must be accepted (architect step 2)"
            );
        });
    }

    #[test]
    fn boltzmann_from_env_epsilon_at_one_accepted() {
        with_env_isolated(|| {
            // epsilon = 5/5 = 1 is INSIDE [0, 1] (always-explore boundary) → accepted.
            std::env::set_var("BOLTZMANN_EPSILON_NUM", "5");
            std::env::set_var("BOLTZMANN_EPSILON_DEN", "5");
            let p = BoltzmannMaskPolicy::from_env();
            assert_eq!(
                (p.epsilon_exploration_num, p.epsilon_exploration_den),
                (5, 5),
                "epsilon = 1 is inside [0, 1] and must be accepted (architect step 2; always-explore boundary)"
            );
        });
    }

    #[test]
    fn boltzmann_policy_zero_decimal_float_substring() {
        // Defense-in-depth: enforce that no field type accidentally accepts
        // a decimal-float-typed value. This is a structural assertion (the
        // halt-trigger #4 file scan is the canonical fence for the module).
        let p = BoltzmannMaskPolicy::default();
        let json = serde_json::to_string(&p).unwrap();
        assert!(
            !json.contains('.'),
            "BoltzmannMaskPolicy JSON must not contain decimal points (integer-rational only)"
        );
    }
}
